// resources/js/layouts/index.tsx
import Footer from '@/components/Footer';
import Header from '@/components/Header';
import { Head, usePage } from '@inertiajs/react';
import React from 'react';

interface IProps {
  children: React.ReactNode;
}

export default function Layout({ children }: IProps) {
  const {
    props: { flash },
    component,
  } = usePage();
  const { message, type } = flash;

  return (
    <>
      <Head title={component} />
      <Header />
      <main className={'main'}>
        {message ? (
          <div className={`flash-message ${type}`}>{message}</div>
        ) : null}
        {children}
      </main>
      <Footer />
    </>
  );
}

// resources/js/layouts/index.vue
<script setup lang="ts">
import Footer from '@components/Footer/index.vue';
import Header from '@components/Header/index.vue';
import { usePage } from '@inertiajs/vue3';

const { flash } = usePage().props;
</script>

<template>
  <Header />
  <main class="main">
    <!-- Flash message -->
    <!-- TODO: Create a component for this -->
    <div
      v-if="flash.message"
      :class="['flash-message', `flash-message-${flash.type}`]"
    >
      {{ flash.message }}
    </div>
    <slot></slot>
  </main>
  <Footer />
</template>
